[phases.setup]
nixPkgs = [
  "chromium",
  "freetype",
  "fontconfig",
  "glib",
  "nss",
  "alsaLib",
  "xorg.libxshmfence",
  "xorg.libxrandr",
  "xorg.libxcomposite",
  "xorg.libxdamage",
  "xorg.libxfixes",
  "xorg.libxcb",
  "xorg.libxext",
  "xorg.libX11",
  "cups",
  "dbus",
  "gtk3",
  "pango",
  "atk",
  "cairo",
  "gdk-pixbuf"
] 