[phases.setup]
nixPkgs = [
  "chromium",
  "freetype",
  "fontconfig",
  "glib",
  "nss",
  "alsa-lib",
  "xorg.libXshmfence",
  "xorg.libXrandr",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXfixes",
  "xorg.libXcb",
  "xorg.libXext",
  "xorg.libX11",
  "cups",
  "dbus",
  "gtk3",
  "pango",
  "atk",
  "cairo",
  "gdk-pixbuf"
] 

[phases.setup.env]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"

[phases.build]
cmds = [
  "echo 'Finding Chromium path...'",
  "CHROME_PATH=$(which chromium 2>/dev/null || which chromium-browser 2>/dev/null || find /nix/store -name chromium-browser -o -name chromium | head -n 1 2>/dev/null)",
  "echo \"Found Chrome at: $CHROME_PATH\"",
  "echo \"export CHROMIUM_PATH=$CHROME_PATH\" >> ~/.bashrc"
]

[start]
cmd = "node src/server.js" 