[phases.setup]
nixPkgs = [
  "chromium",
  "freetype",
  "fontconfig",
  "glib",
  "nss",
  "alsa-lib",
  "xorg.libxshmfence",
  "xorg.libxrandr",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libxfixes",
  "xorg.libxcb",
  "xorg.libXext",
  "xorg.libX11",
  "cups",
  "dbus",
  "gtk3",
  "pango",
  "atk",
  "cairo",
  "gdk-pixbuf"
] 